version: "3.4"

volumes:
  astro_node_modules:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - programming-backend
      - programming-frontend
    ports:
      - 7800:7800

  python-grader:
    build: python-grader
    image: python-grader
    restart: "no"
    volumes:
      - ./python-grader/:/app
    depends_on:
      - mq
      - database
      - flyway
    env_file:
      - project.env
    deploy:
      replicas: 2

  programming-backend:
    build: programming-backend
    image: programming-backend
    restart: "no"
    volumes:
      - ./programming-backend/:/app
      - ./app-cache/:/app-cache
    expose:
      - 7777
    depends_on:
      - database
      - flyway
      - mq
      - redis
      - python-grader
    env_file:
      - project.env
  
  database:
    container_name: database-server
    image: postgres:14.1
    restart: unless-stopped
    env_file:
      - project.env
    ports:
      - "5432:5432"  # 将容器的 5432 端口映射到主机的 5432 端口

  programming-frontend:
    build: 
      context: programming-frontend
      dockerfile: Dockerfile.prod
    image: programming-frontend-prod
    restart: "on-failure"
    volumes:
      - ./programming-frontend/:/app
      - astro_node_modules:/app/node_modules
    expose:
      - 3000
    depends_on:
      - programming-backend

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env

  mq:
    image: rabbitmq:3-management
    restart: "no"
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - project.env
    deploy:
      restart_policy:
        condition: on-failure
        delay: "5s"
        max_attempts: 5
        window: "30s"
  
  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
  
  e2e-playwright:
    entrypoint: "/bin/true"
    build: e2e-playwright
    image: e2e-playwright
    network_mode: host
    depends_on:
      - nginx
    volumes:
      - ./e2e-playwright/tests:/e2e-playwright/tests