# 使用官方的 Python 镜像作为基础镜像
FROM python:3.9-slim

# 设置工作目录
WORKDIR /app

# 复制 requirements.txt 并安装依赖
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

# 复制应用程序代码
COPY main.py .


# 设置环境变量
ENV PYTHONUNBUFFERED=1

# 运行 Python 脚本
CMD ["python3", "main.py"]
